Repository Phaneron97/BDA_proj_rooftiles, pull requests merged in 2024-03, with the labels that each got.

#17 Feature visualize aspect ratios
  code/data_analysis/aspect_ratio_plotter.py
  code/data_analysis/data_analysis_visuals/aspect_ratio_result.png
  code/data_analysis/data_analysis_visuals/rescale_result.png
  code/data_analysis/extension_converter.py
Labels: Feature

#19 Resize keep ratio
  .gitignore
  code/data_analysis/data_analysis_resize_all_keep_ratio.py
Labels: High, Medium, E:M

#26 Feature normalization PR
  code/data_analysis/normalization.py
  code/data_analysis/normalization_converter.py
  code/data_analysis/readme.txt
Labels: Feature, High, E:M

#28 data augmentation.py + images inside data_analysis_visuals
  code/data_analysis/augmentation.py
  code/data_analysis/data_analysis_visuals/d0000_b_blw_g_OVH (5)_horizontal_flip.jpg
  code/data_analysis/data_analysis_visuals/d0000_b_blw_g_OVH (5)_random_rotation.jpg
  code/data_analysis/data_analysis_visuals/d0000_b_blw_g_OVH (5)_random_zoom.jpg
  code/data_analysis/data_analysis_visuals/d0000_b_blw_g_OVH (5)_vertical_flip.jpg
Labels: Feature

#33 added explanation
  data_analysis_report_document/Images/square_dataset/square0.JPG
  data_analysis_report_document/hoofdstukken/changes.tex
Labels: Medium, E:M, Documentation

#42 38 stratified dataset split
  code/data_analysis/stratified_splitter.py
Labels: Feature, Critical, E:L

#47 36 optimizing augmentation file
  code/data_analysis/augmentation.py
Labels: Improvement, Medium

#57 Update augmentation.py
  code/data_analysis/augmentation.py
Labels: Improvement, Critical

#49 Create vgg_train.py
  code/modelconcepts/VGG/vgg_train.py
Labels: Feature, Critical, High, E:H
